export const actionTypes = {
    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',
    CHANGE_THEME: 'CHANGE_THEME',
    GET_DATA_FROM_LOCALSTORAGE: 'GET_DATA_FROM_LOCALSTORAGE',
    GET_DATA_FROM_API: 'GET_DATA_FROM_API',
    ADD_ITEM_TO_SELECTED: 'ADD_ITEM_TO_SELECTED',
    COMPLETE_SET: 'COMPLETE_SET',
    START_NEW_SET: 'START_NEW_SET',
    STOP_TIMER: 'STOP_TIMER',
}
